### ISSUE TITLE
If a user revokes access it crashes

### ISSUE THREAD

**Issue by greenfrogs** [aarondcoleman/Fitbit.NET#48] opened 2015-08-02 16:15 UTC
If a user revokes access it crashes:

Under HandleResponse it throws an exception:

Additional information: Http Error:Unauthorized

**Comment by WestDiscGolf** [comment] 2015-08-02 20:10
Thanks for logging this issue. I wonder if you can provide some more details to aid with resolving the issue.

Is this after a previously successful request to a resource has been processed?

Version 1 or the new async v2?

Can you provide full reproduction steps please?

**Comment by greenfrogs** [comment] 2015-08-02 20:59
To reproduce:
Open the sample desktop app
Input the required information
When you run it it will then authenticate with fitbit (web browser)
This is then completed and the user inputs the code received into the program
Close the application
Go to the https://www.fitbit.com/user/profile/apps
and the revoke access to the app

If you then restart the program it throws an exception

**Comment by WestDiscGolf** [comment] 2015-08-03 07:55
Look at the LoadCredentals method in the sample application, the credentials are stored in a local xml file which can be deleted.

**Comment by WestDiscGolf** [comment] 2015-10-24 15:45
@greenfrogs Did this resolve your issue?

**Comment by aarondcoleman** [comment] 2016-01-22 19:36
since we haven't heard back, closing this for now. Plus, time better spend moving towards V2 since V1 is going to stop working in a few months anyways when Fitbit kills OAuth 1.0

**Closed by aarondcoleman** 2016-01-22 19:36 UTC
