### ISSUE TITLE
redirect_url mismatch error when exchanging code for token

### ISSUE THREAD

**Issue by atbyrd** [aarondcoleman/Fitbit.NET#193] opened 2017-02-01 15:13 UTC
I'm trying to implement exchanging a code for a token in my WebApi application with Fitbit. I keep getting the exception, `Message = "Redirect_uri mismatch: http://localhost:49294/api/oauth2/callback?code=ba6de3....2b41e5. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."`

### RequestUserAuthorizationUrl

    string authorizationLink;
    try
    {
        string[] scopes = {"profile", "activity", "heartrate", "weight", "location", "sleep", "nutrition"};
        authorizationLink = Authenticator().GenerateAuthUrl(scopes);
    }
    catch (Exception e)
    {
        AppUtils.LogException(" FitbitHandler/RequestUserAuthorizationUrl ", e);
        authorizationLink = string.Empty;
    }
    return authorizationLink;

### GetUserToken

    public async Task<OAuth2AccessToken> GetUserToken(string code)
    {
        if (_requestToken != null)
            return _requestToken;
    
        _requestToken = await Authenticator().ExchangeAuthCodeForAccessTokenAsync(code);
        return _requestToken;
    }

### Authenticator

    private OAuth2Helper Authenticator()
    {
        var appCredentials = new FitbitAppCredentials
        {
           ClientId = _consumerKey,
           ClientSecret = _consumerSecret
        };
       return new OAuth2Helper(appCredentials, CallbackUrl);
    }
### Callback @ dev.fitbit.com

    http://localhost:49294/api/oauth2/callback

[Stackoverflow](http://stackoverflow.com/questions/41983016/redirect-url-mismatch-error-when-exchanging-code-for-token)

**Comment by aarondcoleman** [comment] 2017-05-17 20:29
I'm not able to reproduce this. @atbyrd is this still an issue? I'm closing this now to try to clean up known issues, if you can give a little more info on repro I'll re-open it.

**Closed by aarondcoleman** 2017-05-17 20:29 UTC
