### ISSUE TITLE
For V2 the current constructors need to be removed ...

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#72] opened 2016-01-27 21:16 UTC
... and replaced with something more appropriate.

The below is too much and clutters up `FitbitClient.cs`

```
        public FitbitClient(IAuthorization authorization, HttpClient httpClient = null)
        {
            if (authorization == null)
                throw new ArgumentNullException(nameof(authorization), "Authorization can not be null; please provide an Authorization instance.");

            Authorization = authorization;

            if (httpClient == null)
                this.HttpClient = new HttpClient();
            else
                this.HttpClient = httpClient;

            this.HttpClient = authorization.CreateAuthorizedHttpClient(); //use whatever authorization method to provide the HttpClient

        }


        /// <summary>
        /// Use this constructor if an authorized httpclient has already been setup and accessing the resources is what is required.
        /// </summary>
        /// <param name="httpClient"></param>
        [Obsolete]
        public FitbitClient(HttpClient httpClient) : this(string.Empty, string.Empty, string.Empty, string.Empty, httpClient)
        {
        }

        /// <summary>
        /// Use this constructor if the access tokens and keys are known. A httpclient with the correct authorizaton information will be setup to use in the calls.
        /// </summary>
        /// <param name="consumerKey"></param>
        /// <param name="consumerSecret"></param>
        /// <param name="accessToken"></param>
        /// <param name="accessSecret"></param>
        [Obsolete]
        public FitbitClient(string consumerKey, string consumerSecret, string accessToken, string accessSecret) : this(consumerKey, consumerSecret, accessToken, accessSecret, httpClient: null)
        {
            // note: do not remove the httpclient optional parameter above, even if resharper says you should, as otherwise it will make a cyclic constructor call .... which is bad!
        }

        /// <summary>
        /// Private base constructor which takes it all and constructs or throws exceptions as appropriately
        /// </summary>
        /// <param name="consumerKey"></param>
        /// <param name="consumerSecret"></param>
        /// <param name="accessToken"></param>
        /// <param name="accessSecret"></param>
        /// <param name="httpClient"></param>
        [Obsolete]
        private FitbitClient(string consumerKey, string consumerSecret, string accessToken, string accessSecret, HttpClient httpClient = null)
        {
            HttpClient = httpClient;
            if (HttpClient == null)
            {
                #region Parameter checking
                if (string.IsNullOrWhiteSpace(consumerKey))
                {
                    throw new ArgumentNullException(nameof(consumerKey), "ConsumerKey must not be empty or null");
                }

                if (string.IsNullOrWhiteSpace(consumerSecret))
                {
                    throw new ArgumentNullException(nameof(consumerSecret), "ConsumerSecret must not be empty or null");
                }

                if (string.IsNullOrWhiteSpace(accessToken))
                {
                    throw new ArgumentNullException(nameof(accessToken), "AccessToken must not be empty or null");
                }

                if (string.IsNullOrWhiteSpace(accessSecret))
                {
                    throw new ArgumentNullException(nameof(accessSecret), "AccessSecret must not be empty or null");
                }
                #endregion

                HttpClient = AsyncOAuth.OAuthUtility.CreateOAuthClient(consumerKey, consumerSecret, new AsyncOAuth.AccessToken(accessToken, accessSecret));
            }
        }
```

**Comment by mxa0079** [comment] 2016-01-28 18:33
Another issue I noticed with the constructor is that if I pass an IAuthorization and an httpclient, the httpclient is ignored -- this is unexpected/obscure behavior that we should ignore. I was going to log it as an issue, but this one seems to take precedence.

**Comment by mxa0079** [comment] 2016-01-28 18:33
Time to introduce a Factory?

**Comment by WestDiscGolf** [comment] 2016-01-28 23:01
I'm hoping when we've got a better idea of what's going on with authorization as oauth 1 is being dropped the issue with IAuthorization and constructors will work itself out.

As discussed the constructor has to be simple with optional "plugin" to allow people to get up and running quickly with the library

**Comment by mxa0079** [comment] 2016-02-03 18:34
Closing as this is duplicate of #82 and that issue has a longer discussion.

**Closed** 2016-02-03 18:34 UTC
