### ISSUE TITLE
Is this project out-dated? I am not able to recieve any info from fitbit.

### ISSUE THREAD

**Issue by Nisthar** [aarondcoleman/Fitbit.NET#51] opened 2015-09-09 11:29 UTC
I think this project is outdated as this no longer returning anything from fitbit. Also fitbit no longer support xml  which this library uses. Fitbit only returns data in json format. Any way to make this library work by editing it?

**Comment by WestDiscGolf** [comment] 2015-09-09 14:15
Hi Nisthar,

This project is not outdated and we are currently working on version 2 to support all the new goodness and the json data returned for the newer end points.

Fitbit does still currently support xml for the older end points and will continue to support them through oauth 1.0a until a time it will be deprecated - https://community.fitbit.com/t5/Web-API/August-2015-Web-API-Changes/m-p/906005#U906005

If you want to only use json result then please check out the v2 async branch for the new work.

Thanks

**Comment by Nisthar** [comment] 2015-09-09 15:08
But i am not getting any info back from fitbit. I need to get all user's
weight of the last month. But its showing nothing on the weight API page of
the sample project.

Sorry for my bad english.

**Comment by WestDiscGolf** [comment] 2015-09-10 11:20
No worries, here to help :)

Which method are you calling and can you call other methods and return data (to try and rule out authorisation issues)?

**Comment by Nisthar** [comment] 2015-09-10 12:05
Thanks for helping.

The authentication works and i am able to login to my account. But i can't see anything in the weight API page. 
I am testing it out using the samplemvc that comes with this project. I had got a couple of errors like "Parse Error (samplemvc.web.helpers not found)", etc. Had to change versions of assemblies to get it work.

**Comment by WestDiscGolf** [comment] 2015-09-11 08:19
Hi,

I have been able to access the weights from the past month with the xml end point doing the following:

1) Clone the repository and use the master branch (https://github.com/aarondcoleman/Fitbit.NET.git)
2) Update the SampleWebMVC application to be .net 4.5.2
3) Update Microsoft.AspNet.Mvc, Microsoft.AspNet.Razor, Microsoft.AspNet.WebPages and the RestSharp client packages to the latest
4) Add my consumer key and consumer secret to the web.config
5) Run the application
6) Log in to fitbit
7) When the authentication returns to the application I clicked "View Last Month Weight (Body API)"

I'm unable to reproduce your error :-( Please provide some more information and I will try to help.

Thanks

**Comment by Nisthar** [comment] 2015-09-11 11:01
Can you tell how to do the 2nd and 3rd step? Sorry i am new to ASP.NET. I know C#

**Comment by WestDiscGolf** [comment] 2015-09-11 11:06
Sure :-)

Step 2 - right click the SampleWebMVC project > Properties > and in the application tab you change the target framework in the drop down
Step 3 - right click the SampleWebMVC project > Manage Nuget Packages > select updates, find the 4 packages and update them

Hope this helps

**Comment by Nisthar** [comment] 2015-09-11 11:12
I am getting this error when opening the project file.
The imported project "F:\fitbit\FitBit.NET\SampleMVC\.nuget\nuget.targets"
was not found.Confirm that the path in the <import> decalaration is correct
and the file exists on the path.

**Comment by aarondcoleman** [comment] 2015-09-12 01:58
This isn't a library issue. You've put this on an F: drive and the paths in the original solution don't match. See this article:
http://stackoverflow.com/questions/13975682/msbuild-error-finding-the-nuget-targets-file

I'm inclined to close this issue tag as this really isn't the venue for one-on-one support.

Thanks,
--Aaron

**Comment by Nisthar** [comment] 2015-09-12 04:24
Sorry, I didn't see a solution in that link,
Can you please tell me where to put the solution files?

**Comment by fireole** [comment] 2015-09-12 05:02
Aaron, i think you should close this ticket!

Nisthar, please give it a try!  Just a little effort.

On Fri, Sep 11, 2015 at 9:24 PM, Nisthar <notifications@github.com> wrote:

> Sorry, I didn't see a solution in that link,
> Can you please tell me where to put the solution files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aarondcoleman/Fitbit.NET/issues/51#issuecomment-139711959>
> .
>



-- 
Antonio Olander

**Comment by aarondcoleman** [comment] 2015-09-12 05:11
Right. Nisthar, please limit issues filling against the project to specific issues that may need code improvements from contributors.

**Closed by aarondcoleman** 2015-09-12 05:11 UTC

**Comment by Nisthar** [comment] 2015-09-12 05:16
Thanks for the help.
